# Generated by Django 6.1.1 on 2026-09-27 13:53

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Faculty', 'Staff', 'Researcher', 'Leadership'.", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier auto-generated from name. Used for filtering.', max_length=110, unique=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in category lists.')),
            ],
            options={
                'verbose_name': 'Person Category',
                'verbose_name_plural': 'Person Categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text shown above the people grid.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Person Index Page',
                'verbose_name_plural': 'Person Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, help_text="Job title or role, e.g. 'Associate Professor of Economics'.", max_length=200)),
                ('biography', wagtail.fields.StreamField([('rich_text', 0), ('image', 5)], blank=True, block_lookup={0: ('apps.core.blocks.RichBodyBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descriptive alt text for screen readers. Leave blank only for decorative images.', 'max_length': 200, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Full-width image', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('alt_text', 2), ('caption', 3), ('full_width', 4)]], {})}, help_text='Full biography. Supports rich text sections and images.')),
                ('research_interests', wagtail.fields.RichTextField(blank=True, help_text='Research areas, specialisations, or academic interests.')),
                ('email', models.EmailField(blank=True, help_text="Shown publicly only if 'Show contact publicly' is enabled.", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Shown publicly only if 'Show contact publicly' is enabled.", max_length=30)),
                ('office_location', models.CharField(blank=True, help_text='Room number, building, or campus location. Always shown publicly.', max_length=200)),
                ('is_public_contact', models.BooleanField(default=False, help_text='When enabled, email and phone are displayed on the public profile. Disable to keep contact details internal only.', verbose_name='Show contact publicly')),
                ('ordering', models.IntegerField(default=0, help_text='Lower numbers appear first within category/index listings.')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select one or more categories (Faculty, Staff, Researcher, etc.).', to='people.personcategory')),
                ('department', models.ForeignKey(blank=True, help_text='Primary department affiliation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='departments.departmentpage')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('profile_photo', models.ForeignKey(blank=True, help_text='Headshot image. Square crop recommended (minimum 400×400 px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['ordering', 'last_name', 'first_name'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
