# Generated by Django 6.1.1 on 2026-09-27 13:53

import datetime
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category display name shown on the site.', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier used for filtering (auto-populated from name).', max_length=100, unique=True)),
                ('icon', models.ForeignKey(blank=True, help_text='Optional icon image displayed alongside the category label.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News category',
                'verbose_name_plural': 'News categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text displayed above the news grid.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('headline', models.CharField(help_text='Article headline displayed as the main title.', max_length=300)),
                ('summary', models.TextField(blank=True, help_text='Brief summary for listing pages (up to 500 characters).', max_length=500)),
                ('body', wagtail.fields.StreamField([('heading', 3), ('rich_text', 4), ('image', 9), ('quote', 12), ('call_to_action', 17), ('document_list', 21), ('notice', 24), ('accordion', 29), ('statistics', 34), ('embed', 35), ('link_list', 43)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor for in-page links (e.g. 'contact-us').", 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor_id', 2)]], {}), 4: ('apps.core.blocks.RichBodyBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descriptive alt text for screen readers. Leave blank only for decorative images.', 'max_length': 200, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Full-width image', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('alt_text', 6), ('caption', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribution', 11), ('attribution_title', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Learn more', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (used if no page selected).', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 13), ('button_label', 14), ('button_page', 15), ('button_url', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 11)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 11), ('documents', 20)]], {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information'), ('warning', 'Warning'), ('important', 'Important'), ('success', 'Success')]}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 24: ('wagtail.blocks.StructBlock', [[('notice_type', 22), ('title', 11), ('text', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote']}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '500+', '₹12 Cr'", 'max_length': 50, 'required': True}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 32: ('wagtail.blocks.StructBlock', [[('value', 30), ('label', 31), ('description', 11)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'max_num': 6, 'min_num': 2}), 34: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 33)]], {}), 35: ('apps.core.blocks.EmbedBlock', (), {}), 36: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the page title as link label.', 'max_length': 200, 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('page', 36), ('label', 37)]], {}), 39: ('wagtail.blocks.URLBlock', (), {'required': True}), 40: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('url', 39), ('label', 0), ('opens_new_tab', 40)]], {}), 42: ('wagtail.blocks.StreamBlock', [[('internal', 38), ('external', 41)]], {}), 43: ('wagtail.blocks.StructBlock', [[('title', 11), ('links', 42)]], {})}, help_text='Main article body content.')),
                ('author_name', models.CharField(blank=True, help_text='Author display name shown on the article.', max_length=200)),
                ('publication_date', models.DateField(db_index=True, default=datetime.date.today, help_text='Date shown publicly on the article and used for sorting.')),
                ('categories', models.ManyToManyField(blank=True, help_text='One or more categories this article belongs to.', related_name='news_pages', to='news.newscategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Hero image for the article (used in listings and social sharing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News article',
                'verbose_name_plural': 'News articles',
                'ordering': ['-publication_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
