# Generated by Django 6.1.1 on 2026-09-27 13:53

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Announcements index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnnouncementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('summary', models.TextField(help_text='Brief announcement text (shown on listings and homepage).', max_length=500)),
                ('body', wagtail.fields.StreamField([('heading', 3), ('rich_text', 4), ('image', 9), ('quote', 12), ('call_to_action', 17), ('document_list', 21), ('notice', 24), ('accordion', 29), ('statistics', 34), ('embed', 35), ('link_list', 43)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor for in-page links (e.g. 'contact-us').", 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor_id', 2)]], {}), 4: ('apps.core.blocks.RichBodyBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descriptive alt text for screen readers. Leave blank only for decorative images.', 'max_length': 200, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Full-width image', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('alt_text', 6), ('caption', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribution', 11), ('attribution_title', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Learn more', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (used if no page selected).', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 13), ('button_label', 14), ('button_page', 15), ('button_url', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 11)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 11), ('documents', 20)]], {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information'), ('warning', 'Warning'), ('important', 'Important'), ('success', 'Success')]}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 24: ('wagtail.blocks.StructBlock', [[('notice_type', 22), ('title', 11), ('text', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote']}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '500+', '₹12 Cr'", 'max_length': 50, 'required': True}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 32: ('wagtail.blocks.StructBlock', [[('value', 30), ('label', 31), ('description', 11)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'max_num': 6, 'min_num': 2}), 34: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 33)]], {}), 35: ('apps.core.blocks.EmbedBlock', (), {}), 36: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the page title as link label.', 'max_length': 200, 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('page', 36), ('label', 37)]], {}), 39: ('wagtail.blocks.URLBlock', (), {'required': True}), 40: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('url', 39), ('label', 0), ('opens_new_tab', 40)]], {}), 42: ('wagtail.blocks.StreamBlock', [[('internal', 38), ('external', 41)]], {}), 43: ('wagtail.blocks.StructBlock', [[('title', 11), ('links', 42)]], {})}, help_text='Optional extended content.')),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Date after which this announcement should no longer be prominently displayed.', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this announcement to the top of listings.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Message shown after form submission.')),
                ('address_block', wagtail.fields.RichTextField(blank=True, help_text='Formatted address for display.')),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL (no JavaScript tracking version preferred).')),
                ('from_address', models.EmailField(help_text='The email address form submissions are sent from.', max_length=254, verbose_name='From address')),
                ('to_address', models.EmailField(help_text='Email address that receives submitted forms.', max_length=254, verbose_name='To address')),
                ('subject', models.CharField(default='Contact form submission — Nakashara', max_length=200, verbose_name='Subject')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='content.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Notices index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('notice_number', models.CharField(blank=True, help_text='Official notice reference number (e.g. REG/2026/001).', max_length=100)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('heading', 3), ('rich_text', 4), ('image', 9), ('quote', 12), ('call_to_action', 17), ('document_list', 21), ('notice', 24), ('accordion', 29), ('statistics', 34), ('embed', 35), ('link_list', 43)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor for in-page links (e.g. 'contact-us').", 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor_id', 2)]], {}), 4: ('apps.core.blocks.RichBodyBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descriptive alt text for screen readers. Leave blank only for decorative images.', 'max_length': 200, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Full-width image', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('alt_text', 6), ('caption', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribution', 11), ('attribution_title', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Learn more', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (used if no page selected).', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 13), ('button_label', 14), ('button_page', 15), ('button_url', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 11)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 11), ('documents', 20)]], {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information'), ('warning', 'Warning'), ('important', 'Important'), ('success', 'Success')]}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 24: ('wagtail.blocks.StructBlock', [[('notice_type', 22), ('title', 11), ('text', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote']}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '500+', '₹12 Cr'", 'max_length': 50, 'required': True}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 32: ('wagtail.blocks.StructBlock', [[('value', 30), ('label', 31), ('description', 11)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'max_num': 6, 'min_num': 2}), 34: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 33)]], {}), 35: ('apps.core.blocks.EmbedBlock', (), {}), 36: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the page title as link label.', 'max_length': 200, 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('page', 36), ('label', 37)]], {}), 39: ('wagtail.blocks.URLBlock', (), {'required': True}), 40: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('url', 39), ('label', 0), ('opens_new_tab', 40)]], {}), 42: ('wagtail.blocks.StreamBlock', [[('internal', 38), ('external', 41)]], {}), 43: ('wagtail.blocks.StructBlock', [[('title', 11), ('links', 42)]], {})})),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Short introduction shown prominently at the top of the page.')),
                ('body', wagtail.fields.StreamField([('heading', 3), ('rich_text', 4), ('image', 9), ('quote', 12), ('call_to_action', 17), ('document_list', 21), ('notice', 24), ('accordion', 29), ('statistics', 34), ('embed', 35), ('link_list', 43)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor for in-page links (e.g. 'contact-us').", 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor_id', 2)]], {}), 4: ('apps.core.blocks.RichBodyBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descriptive alt text for screen readers. Leave blank only for decorative images.', 'max_length': 200, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Full-width image', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('alt_text', 6), ('caption', 7), ('full_width', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribution', 11), ('attribution_title', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Learn more', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (used if no page selected).', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 13), ('button_label', 14), ('button_page', 15), ('button_url', 16)]], {}), 18: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('document', 18), ('label', 11)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 11), ('documents', 20)]], {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information'), ('warning', 'Warning'), ('important', 'Important'), ('success', 'Success')]}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 24: ('wagtail.blocks.StructBlock', [[('notice_type', 22), ('title', 11), ('text', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote']}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '500+', '₹12 Cr'", 'max_length': 50, 'required': True}), 31: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 32: ('wagtail.blocks.StructBlock', [[('value', 30), ('label', 31), ('description', 11)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'max_num': 6, 'min_num': 2}), 34: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 33)]], {}), 35: ('apps.core.blocks.EmbedBlock', (), {}), 36: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the page title as link label.', 'max_length': 200, 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('page', 36), ('label', 37)]], {}), 39: ('wagtail.blocks.URLBlock', (), {'required': True}), 40: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 41: ('wagtail.blocks.StructBlock', [[('url', 39), ('label', 0), ('opens_new_tab', 40)]], {}), 42: ('wagtail.blocks.StreamBlock', [[('internal', 38), ('external', 41)]], {}), 43: ('wagtail.blocks.StructBlock', [[('title', 11), ('links', 42)]], {})})),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Standard page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
