# Generated by Django 6.1.1 on 2026-09-27 13:53

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category display name shown on the site.', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier used for filtering (auto-populated from name).', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Document category',
                'verbose_name_plural': 'Document categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Career index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('position_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('research', 'Research'), ('postdoc', 'Post-Doctoral'), ('phd', 'PhD'), ('other', 'Other')], default='other', help_text='Type of position being advertised.', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Hiring department or school.', max_length=200)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Full position description, responsibilities, and context.')),
                ('qualifications', wagtail.fields.RichTextField(blank=True, help_text='Required and preferred qualifications for applicants.')),
                ('closing_date', models.DateField(blank=True, db_index=True, help_text='Application deadline.', null=True)),
                ('application_url', models.URLField(blank=True, help_text='External application portal URL.')),
                ('application_email', models.EmailField(blank=True, help_text='E-mail address to send applications to (if no portal URL).', max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], db_index=True, default='open', help_text='Current recruitment status.', max_length=20)),
                ('document_file', models.ForeignKey(blank=True, help_text='Detailed job description or advertisement document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Career posting',
                'verbose_name_plural': 'Career postings',
                'ordering': ['closing_date', '-first_published_at'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocumentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text displayed above the document listing.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Document index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('description', models.TextField(blank=True, help_text='Brief description of the document (up to 500 characters).', max_length=500)),
                ('document_type', models.CharField(choices=[('report', 'Report'), ('policy', 'Policy'), ('form', 'Form'), ('circular', 'Circular'), ('notice', 'Notice'), ('annual_report', 'Annual Report'), ('other', 'Other')], default='other', help_text='Classification for filtering and display.', max_length=30)),
                ('publication_date', models.DateField(blank=True, db_index=True, help_text='Date the document was officially published or released.', null=True)),
                ('department', models.CharField(blank=True, help_text='Issuing department or office.', max_length=200)),
                ('version', models.CharField(blank=True, help_text="Document version string (e.g. 'v2.1', 'Rev 3').", max_length=50)),
                ('language', models.CharField(blank=True, default='English', help_text='Primary language of the document.', max_length=50)),
                ('is_public', models.BooleanField(default=True, help_text='Public documents appear in the document listing. Private documents are hidden from public listings but remain accessible via direct URL. Use Wagtail collection permissions for true access restriction.')),
                ('categories', models.ManyToManyField(blank=True, help_text='One or more categories this document belongs to.', related_name='document_pages', to='documents.documentcategory')),
                ('document_file', models.ForeignKey(blank=True, help_text="Uploadable document file from the Wagtail document library. For restricted access, use a protected Wagtail collection and set 'Is public' to False on this page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Optional cover or preview thumbnail image for listings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Document page',
                'verbose_name_plural': 'Document pages',
                'ordering': ['-publication_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text displayed above the publications listing.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Publication index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('authors', models.CharField(help_text='Author(s) — separate multiple names with commas or semicolons.', max_length=400)),
                ('publication_year', models.PositiveSmallIntegerField(db_index=True, help_text='Four-digit publication year.')),
                ('journal_or_publisher', models.CharField(blank=True, help_text='Journal name, conference name, or publisher.', max_length=300)),
                ('doi_or_url', models.URLField(blank=True, help_text='Digital Object Identifier (DOI) link or external publisher URL.')),
                ('abstract', models.TextField(blank=True, help_text='Publication abstract or summary.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search and discovery.', max_length=300)),
                ('publication_type', models.CharField(choices=[('journal_article', 'Journal Article'), ('conference_paper', 'Conference Paper'), ('book', 'Book'), ('book_chapter', 'Book Chapter'), ('report', 'Report'), ('thesis', 'Thesis'), ('other', 'Other')], default='journal_article', help_text='Classification of the publication.', max_length=30)),
                ('document_file', models.ForeignKey(blank=True, help_text='Full-text PDF or document file, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_year'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Report index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('report_year', models.PositiveSmallIntegerField(db_index=True, help_text='Four-digit year this report covers.')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the report (up to 500 characters).', max_length=500)),
                ('document_file', models.ForeignKey(blank=True, help_text='Downloadable report file (PDF recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('report_image', models.ForeignKey(blank=True, help_text='Cover image or representative illustration for the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-report_year'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TenderIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Tender index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TenderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('meta_description', models.CharField(blank=True, help_text='Brief description for search engines (150–320 characters).', max_length=320)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if this page has a preferred URL.')),
                ('robots_noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('reference_number', models.CharField(blank=True, help_text='Official tender reference or notice number.', max_length=100)),
                ('tender_type', models.CharField(choices=[('goods', 'Goods'), ('works', 'Works'), ('services', 'Services'), ('consultancy', 'Consultancy'), ('other', 'Other')], default='other', help_text='Procurement category for this tender.', max_length=20)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Full tender description, scope, and terms.')),
                ('opening_date', models.DateField(blank=True, help_text='Date from which tender documents become available.', null=True)),
                ('closing_date', models.DateField(blank=True, db_index=True, help_text='Deadline for submission of bids.', null=True)),
                ('estimated_value', models.CharField(blank=True, help_text="Estimated contract value (e.g. '₹25,00,000' or 'USD 50,000').", max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('awarded', 'Awarded')], db_index=True, default='open', help_text='Current status of this tender.', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact e-mail address for tender enquiries.', max_length=254)),
                ('document_file', models.ForeignKey(blank=True, help_text='Tender document package for download.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social sharing image (1200×630 px recommended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-closing_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
