# Generated by Django 6.1.1 on 2026-10-09 14:45

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920×800 px or wider). Used if no slides are added below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='HomePageHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tag', models.CharField(blank=True, default='Featured Program', help_text="Badge label above headline (e.g. 'Academic Excellence', 'Admissions Open').", max_length=100)),
                ('headline', models.CharField(blank=True, help_text='Slide headline (falls back to main hero headline if blank).', max_length=200)),
                ('subheadline', models.CharField(blank=True, help_text='Slide subheadline (falls back to main hero subheadline if blank).', max_length=400)),
                ('cta_label', models.CharField(blank=True, help_text='CTA button label.', max_length=100)),
                ('cta_url', models.URLField(blank=True, help_text='External URL if no page selected.')),
                ('cta_page', models.ForeignKey(blank=True, help_text='Link to an internal page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL)),
                ('image', models.ForeignKey(blank=True, help_text='Slide background image (1920×800 px or wider).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
