# Generated by Django 6.1.1 on 2026-09-27 13:53

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical / Emergency')], default='info', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Short message displayed in the banner.')),
                ('link_text', models.CharField(blank=True, help_text='Optional link label.', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL.')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert banner',
                'verbose_name_plural': 'Alert banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Footer link group',
                'verbose_name_plural': 'Footer link groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL)),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_settings.footerlinkgroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='Navigation label shown to users.', max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='External URL (used if no page selected).')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in a new browser tab.')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True, help_text='Show this item in the navigation.')),
                ('page', models.ForeignKey(blank=True, help_text='Link to a Wagtail page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL)),
                ('parent', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='site_settings.navmenuitem')),
            ],
            options={
                'verbose_name': 'Navigation menu item',
                'verbose_name_plural': 'Navigation menu items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Nakashara', help_text='Full institution name.', max_length=200)),
                ('institution_short_name', models.CharField(blank=True, help_text='Abbreviated name (e.g. NKSR).', max_length=50)),
                ('tagline', models.CharField(blank=True, help_text='Institutional tagline shown in header/footer.', max_length=300)),
                ('logo_alt_text', models.CharField(blank=True, default='Nakashara logo', help_text='Alt text for the logo image.', max_length=200)),
                ('address_line_1', models.CharField(blank=True, max_length=300)),
                ('address_line_2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email_general', models.EmailField(blank=True, max_length=254)),
                ('email_admissions', models.EmailField(blank=True, max_length=254)),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('footer_copyright_text', models.CharField(blank=True, help_text='Copyright line in footer.', max_length=400)),
                ('footer_note', models.TextField(blank=True, help_text='Optional additional note in footer.')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics GA4 Measurement ID (e.g. G-XXXXXXXXXX). Leave blank to disable.', max_length=50)),
                ('favicon', models.ForeignKey(blank=True, help_text='Favicon (32×32 or 64×64 px, ICO/PNG).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, help_text='Institution logo (SVG or PNG, transparent background).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
