# Generated by Django 6.1.1 on 2026-09-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_accent_color',
            field=models.CharField(blank=True, help_text='Optional hex color to override secondary/accent color (e.g. #D97706 or #E11D48).', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_primary_color',
            field=models.CharField(blank=True, help_text='Optional hex color to override primary brand color (e.g. #1E40AF or #047857).', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('corporate', 'Corporate (Clean Modern Blue & Slate)'), ('emerald', 'Emerald (Academic Deep Green & Mint)'), ('nord', 'Nord (Modern Arctic Slate & Frost)'), ('winter', 'Winter (Crisp Professional Cyan & Ice)'), ('business', 'Business (High-Contrast Corporate Dark)'), ('night', 'Night (Deep Modern Dark)'), ('autumn', 'Autumn (Warm Rust, Bronze & Cream)'), ('luxury', 'Luxury (Dark Gold & Deep Obsidian)'), ('light', 'Light (Default Clean Bright)')], default='corporate', help_text='Color palette and theme for the entire website.', max_length=50),
        ),
    ]
