# Generated by Django 6.1.1 on 2026-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_custom_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('corporate', 'Corporate (Clean Modern Blue & Slate)'), ('emerald', 'Emerald (Academic Deep Green & Mint)'), ('nord', 'Nord (Modern Arctic Slate & Frost)'), ('winter', 'Winter (Crisp Professional Cyan & Ice)'), ('business', 'Business (High-Contrast Corporate Dark)'), ('night', 'Night (Deep Modern Dark)'), ('autumn', 'Autumn (Warm Rust, Bronze & Cream)'), ('luxury', 'Luxury (Dark Gold & Deep Obsidian)'), ('light', 'Light (Default Clean Bright)'), ('acid', 'Acid (Dark Pink & Deep Blue)')], default='corporate', help_text='Color palette and theme for the entire website.', max_length=50),
        ),
    ]
