# Generated by Django 6.1.1 on 2026-10-09 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_sitesettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_accent_color',
            field=models.CharField(blank=True, help_text='Optional hex color to override secondary/accent color (e.g. #B58A48).', max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid 3- or 6-digit hex color code starting with # (e.g. #24466B).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='custom_primary_color',
            field=models.CharField(blank=True, help_text='Optional hex color to override primary brand color (e.g. #24466B).', max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid 3- or 6-digit hex color code starting with # (e.g. #24466B).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('corporate', 'Nakashara Oxford (Institutional Navy, Sage & Gold)'), ('emerald', 'Emerald (Academic Forest Green & Mint)'), ('nord', 'Nord (Modern Arctic Slate & Frost)'), ('winter', 'Winter (Crisp Professional Cyan & Ice)'), ('autumn', 'Autumn (Warm Terracotta, Bronze & Cream)'), ('luxury', 'Luxury (Distinguished Obsidian & Burnished Gold)'), ('business', 'Business (High-Contrast Corporate Dark)'), ('night', 'Night (Deep Modern Academic Dark)'), ('light', 'Light (Clean Editorial Minimalist)')], default='corporate', help_text='Color palette and theme for the entire website.', max_length=50),
        ),
    ]
