# Generated by Django 6.1.1 on 2026-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_sitesettings_custom_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='building_or_campus',
            field=models.CharField(blank=True, help_text='Campus name, locality, or sector.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='directions_info',
            field=models.TextField(blank=True, help_text='Brief visitor guidance, transit routes, or parking details.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='directions_url',
            field=models.URLField(blank=True, help_text='Official Google Maps or transit directions URL.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_accessibility',
            field=models.EmailField(blank=True, help_text='Accessibility officer or compliance contact email.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_reception',
            field=models.EmailField(blank=True, help_text='Front desk, reception, or helpdesk email.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fax_number',
            field=models.CharField(blank=True, help_text='Official institutional facsimile number.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(blank=True, help_text='Short institutional description shown in footer.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(blank=True, default='Monday – Friday: 9:00 AM – 5:00 PM IST', help_text='Standard administrative office hours.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_toll_free',
            field=models.CharField(blank=True, help_text='Toll-free or student helpline telephone number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Primary street address or building number.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Secondary address details (suite, block, floor).', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, help_text='City or municipality.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(blank=True, default='India', help_text='Country name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_admissions',
            field=models.EmailField(blank=True, help_text='Admissions & student inquiries email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_general',
            field=models.EmailField(blank=True, help_text='General institutional inquiry email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(blank=True, help_text='Copyright line shown in footer (defaults to current year + institution name).', max_length=400),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_note',
            field=models.TextField(blank=True, help_text='Optional statutory or accreditation note in footer.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='institution_name',
            field=models.CharField(default='Nakashara', help_text='Full official institution name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='institution_short_name',
            field=models.CharField(blank=True, help_text='Abbreviated name or acronym (e.g. NKSR).', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Main institutional switchboard / telephone number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Alternate telephone number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code or PIN code.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='state',
            field=models.CharField(blank=True, help_text='State, province, or region.', max_length=100),
        ),
    ]
