# Generated by Django 6.1.1 on 2026-10-09 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_building_or_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertbanner',
            name='display_end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional date and time after which this content is no longer displayed. Leave blank for indefinite display.', null=True, verbose_name='Display end'),
        ),
        migrations.AddField(
            model_name='alertbanner',
            name='display_start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time from which this content becomes eligible for display.', verbose_name='Display start'),
        ),
        migrations.AlterField(
            model_name='alertbanner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Enable or disable this content. Inactive content is hidden from all public views.', verbose_name='Active'),
        ),
    ]
